### ISSUE TITLE
Issues using esbuild-java on Windows

### ISSUE THREAD

**Issue by chrisruffalo** [mvnpm/esbuild-java#55]
I am currently having two issues building using the esbuild-java (through Quarkus Web Bundler) on windows.

1) An exception is thrown [from BaseResolver:86](https://github.com/mvnpm/esbuild-java/blob/5c8bc82c8dd9bd58162dcd8fe9c409290f0646b8/src/main/java/io/mvnpm/esbuild/resolve/BaseResolver.java#L86) when the esbuild binary already exists at that path. Deleting it and rerunning allows me to continue but it is a little aggravating.

2) An exception is thrown [from BaseResolver:91](https://github.com/mvnpm/esbuild-java/blob/5c8bc82c8dd9bd58162dcd8fe9c409290f0646b8/src/main/java/io/mvnpm/esbuild/resolve/BaseResolver.java#L91) because I'm not on a POSIX-compliant filesystem. I cannot work around this issue.

I am using cygwin on windows but I don't think that matters. This would fail on any non-compliant filesystem.

**Comment by ia3andy** [comment]
@chrisruffalo I've release the web-bundler 1.1.4, it is now tested on Windows. Thanks ! and let me know if you find more bugs :)
